zeta/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà utilisé sur un autre compte")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $pseudonyme;

    /**
     * @ORM\ManyToMany(targetEntity=Game::class, mappedBy="user")
     */
    private $games;

    /**
     * @ORM\OneToMany(targetEntity=Rating::class, mappedBy="user", orphanRemoval=true)
     */
    private $ratings;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    public function __construct()
    {
        $this->games = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudonyme(): ?string
    {
        return $this->pseudonyme;
    }

    public function setPseudonyme(string $pseudonyme): self
    {
        $this->pseudonyme = $pseudonyme;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->addUser($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->removeElement($game)) {
            $game->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setUser($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getUser() === $this) {
                $rating->setUser(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;
        
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }
}

zeta/src/Controller/RateController.php
<?php

namespace App\Controller;

use App\Entity\Rating;
use App\Form\RatingType;
use App\Repository\RatingRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/rate')]
class RateController extends AbstractController
{
    #[Route('/', name: 'rate_index', methods: ['GET'])]
    public function index(RatingRepository $ratingRepository): Response
    {
        return $this->render('rate/index.html.twig', [
            'ratings' => $ratingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'rate_new', methods: ['GET','POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request): Response
    {
        $rating = new Rating();
        $form = $this->createForm(RatingType::class, $rating);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rating);
            $entityManager->flush();

            return $this->redirectToRoute('rate_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rate/new.html.twig', [
            'rating' => $rating,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'rate_show', methods: ['GET'])]
    public function show(Rating $rating): Response
    {
        return $this->render('rate/show.html.twig', [
            'rating' => $rating,
        ]);
    }

    #[Route('/{id}/edit', name: 'rate_edit', methods: ['GET','POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Rating $rating): Response
    {
        $form = $this->createForm(RatingType::class, $rating);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rate_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rate/edit.html.twig', [
            'rating' => $rating,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'rate_delete', methods: ['POST'])]
    public function delete(Request $request, Rating $rating): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rating->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rating);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rate_index', [], Response::HTTP_SEE_OTHER);
    }
}

zeta/templates/rate/_delete_form.html.twig
<form method="post" action="{{ path('rate_delete', {'id': rating.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rating.id) }}">
    <button class="btn">Delete</button>
</form>

zeta/templates/rate/_form.html.twig
<form class="formRating" name="rating" method="post">
    {{ form_widget(form.description, {'attr': {'placeholder': "Avis de l'utilisateur", 'style': 'max-width:273px; max-height:70px; overflow:none'}})}}
    {{ form_widget(form.rate, {'attr': {'placeholder': "Note de l'utilisateur"}})}}
    <div class="status">
    <label for="status">Status</label>
    {{ form_widget(form.status)}}
    </div>
    
    <button class="btn"><i class="fas fa-check"></i></button>
</form>

zeta/templates/rate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un avis{% endblock %}

{% block body %}
    <div class="backPrevious">
        <a href="{{ path('rate_index') }}"><i class="fas fa-arrow-left"></i></a>
    </div>

    <div class="container-new">
        <div class="newRating">
            <h1>Modifier l'avis</h1>
            {{ include('rate/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
    </div>

    {# {{ include('rate/_delete_form.html.twig') }} #}
{% endblock %}

zeta/templates/rate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les avis{% endblock %}

{% block body %}
<div class="container">
    <h1>Gérer les avis</h1>

    <div class="avisList">
        <table class="table">
        <thead>
            <tr>
                <th>Note</th>
                <th>Description</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rating in ratings %}
            <tr class="avis">
                <td>{{ rating.rate }}</td>
                <td>{{ rating.description }}</td>
                <td>{{ rating.status ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('rate_edit', {'id': rating.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Pas d'avis</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

zeta/templates/rate/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Rating{% endblock %}

{% block body %}
    <h1>Create new Rating</h1>

    {{ include('rate/_form.html.twig') }}

    <a href="{{ path('rate_index') }}">back to list</a>
{% endblock %}

zeta/templates/rate/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rating{% endblock %}

{% block body %}
    <h1>Rating</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ rating.id }}</td>
            </tr>
            <tr>
                <th>username</th>
                <td>{{ user.pseudonyme }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ rating.createdAt ? rating.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Rate</th>
                <td>{{ rating.rate }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ rating.description }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ rating.status ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('rate_index') }}">back to list</a>

    <a href="{{ path('rate_edit', {'id': rating.id}) }}">edit</a>

    {{ include('rate/_delete_form.html.twig') }}
{% endblock %}